### ISSUE TITLE
Can't import file from npm if CDN

### ISSUE THREAD

**Issue by kontyente** [DHTMLX/vue-suite-demo#1]
https://github.com/DHTMLX/vue-suite-demo/blob/85c39fa3b72431e32cc3baf46ee4dae81a68c517/src/components/toolbar/ToolbarCdn.vue#L7

Could you please check this import on line 7 if it makes any sense. 
If CDN, how can this import work?

**Comment by Sorokin-Oleg** [comment]
> https://github.com/DHTMLX/vue-suite-demo/blob/85c39fa3b72431e32cc3baf46ee4dae81a68c517/src/components/toolbar/ToolbarCdn.vue#L7
> 
> Could you please check this import on line 7 if it makes any sense.
> If CDN, how can this import work?

Hello. Yes, this line doesn't make sense. Thanks, we fixed it.
