### ISSUE TITLE
dhx. doesn't exist

### ISSUE THREAD

**Issue by kontyente** [DHTMLX/vue-suite-demo#2]
https://github.com/DHTMLX/vue-suite-demo/blob/933418952c1cb4049359908d645f0246b8ff5134/src/components/toolbar/ToolbarCdn.vue#L16

For some reason the "dhx." doesnt seem a valid argument. Is it possible that the CDN isn't loaded yet?

**Comment by Sorokin-Oleg** [comment]
Hi. It's really weird, but this code works. Try to check the availability of our CDN region by clicking on the link for your site: https://cdn.dhtmlx.com/suite/edge/suite.js

If this is an ESlint message, add the following before this line:
`// eslint-disable-next-line no-undef`
